Update and rename ci(PR).yml to ci(pr).yml

diff --git a/.github/workflows/ci(pr).yml b/.github/workflows/ci(pr).yml
--- a/.github/workflows/ci(pr).yml
+++ b/.github/workflows/ci(pr).yml
@@ -26,7 +26,21 @@ jobs:
 
       - name: Detect package manager
         id: DPM
-        run: "${{ github.workspace }}/DPMcm"
+        run: |
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "::set-output name=manager::yarn"
+            echo "::set-output name=command::install"
+            echo "::set-output name=runner::yarn"
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "::set-output name=manager::npm"
+            echo "::set-output name=command::ci"
+            echo "::set-output name=runner::npx --no-install"
+            exit 0
+          else
+            echo "Unable to determine packager manager"
+            exit 1
+          fi
       
 
   cache:
@@ -57,4 +71,3 @@ jobs:
 
       - name: Build
         run: npm run build
-
